---
title: 'Robot Performance Analysis: Pre and Post Upgrade'
author: "Natnalin Kerdkaew"
date: "2024-06-8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(ggplot2)
Sys.setlocale("LC_TIME", "C")
```

### **Assume**

```{r}
start_time_before <- as.POSIXct("2024-06-01 08:00")
end_time_before <- start_time_before + days(6) - hours(1)
start_time_after <- as.POSIXct("2024-06-07 08:00")
end_time_after <- start_time_after + days(6) - hours(1)

timestamps_before <- seq(from = start_time_before, to = end_time_before, by = "hour")
timestamps_after <- seq(from = start_time_after, to = end_time_after, by = "hour")
set.seed(44) 

# Setting seed for reproducibility
workpieces_before <- sample(40:60, length(timestamps_before), replace = TRUE)
workpieces_after <- sample(50:70, length(timestamps_after), replace = TRUE)
data_before <- data.frame(Time = timestamps_before, Workpieces = workpieces_before, Period = "Before")
data_after <- data.frame(Time = timestamps_after, Workpieces = workpieces_after, Period = "After")

data <- rbind(data_before, data_after)

head(data)
```

### **Summary Statistics**

```{r}
summary(data[data$Period == "Before", "Workpieces"])
summary(data[data$Period == "After", "Workpieces"])

```

### **Data Visualization**

```{r}
ggplot(data, aes(x = as.POSIXct(Time), y = Workpieces, color = Period)) +
  geom_line() +
  labs(title = "Robot Performance Analysis: Pre and Post Upgrade", x = "Day (1-10)", y = "Number of Workpieces Processed Per Hour During 8-Hour Shifts") +
  scale_color_manual(name = "Period", values = c("Before" = "gold", "After" = "purple")) +
  theme_minimal()

```

### **Statistical Analysis**

```{r}
before_data <- data[data$Period == "Before", "Workpieces"]
after_data <- data[data$Period == "After", "Workpieces"]

t_test_result <- t.test(before_data, after_data, paired = TRUE)
print(t_test_result)

```

### **Calculate Mean Workpieces Processed Per Hour**

```{r}
mean_before <- mean(before_data)
mean_after <- mean(after_data)

cat("Average number of workpieces processed per hour before the upgrade:", mean_before, "\n")
cat("Average number of workpieces processed per hour after the upgrade:", mean_after, "\n")

```

### **Interpretation**

```{r}
if (t_test_result$p.value < 0.05) {
  cat("The increase in the number of workpieces processed per hour after the upgrade is statistically significant.\n")
} else {
  cat("There is no statistically significant difference in the number of workpieces processed per hour before and after the upgrade.\n")
}

```


















